# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]

jobs:
  checkout-only:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository without submodules
        uses: actions/checkout@v3
        with:
          submodules: false
